### ISSUE TITLE
application.h missing

### ISSUE THREAD

**Issue by berkley** [Na2l/spark-websocket-server#3]
Hi,
I'm trying to compile this, but application.h appears to be #included in many files but is not in this repository.  Can you add it?

thanks,
chad

**Comment by Na2l** [comment]
Chad, I just updated the source tree, so you don’t; need to any manual work.
just clone the repository and give it a try

**Comment by Na2l** [comment]
Chad, I just updated the source tree, so you don’t; need to any manual work.
just clone the repository and give it a try
